### ISSUE TITLE
hardcode path issue for me 

### ISSUE THREAD

**Issue by gfane1** [syntithenai/voice2llm#1]
Think line 25 of https://github.com/syntithenai/voice2llm/blob/main/docker-compose.yml was my little issue

      - /home/stever/.local/share/nomic.ai/GPT4All:/app/GPT4All #

Also got this but think its sorted now and downloading...be nice if you mentioned how big the file is...but all good :)
![image](https://github.com/syntithenai/voice2llm/assets/20381605/b20d498b-ab9d-4f55-a26c-b375f0d12d87)

**Comment by syntithenai** [comment]
I'd guess the ghcr.io host or your internet connection is bouncing. Try again.
